
services:

  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      my-network:
        aliases:
          - postgres
          - db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - "./postgresql-data:/var/lib/postgresql/data"
    container_name: postgres

  pgadmin:
    image: dpage/pgadmin4:8.14
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    networks:
      my-network:
        aliases:
          - pgadmin
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - "./pgadmin-data:/var/lib/pgadmin"
    container_name: pgadmin
    depends_on:
      - postgres

networks:
  my-network:
    name: my-network
