
services:

  portainer:
    image: portainer/portainer-ce:2.21.5
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    container_name: portainer
